### ISSUE TITLE
7.0以扫描出垃圾，但是清理时依然跳出

### ISSUE THREAD

**Issue by likky** [RuijiePan/FileManager#4]
7.0以扫描出垃圾，但是清理时依然跳出，无法清理。
你可以找台手机试试，我是荣耀6X

**Comment by RuijiePan** [comment]
能把crash发出来看一下吗

**Comment by likky** [comment]
时间	设备名称	类型	PID	标记	消息
09-02 17:42:42.693	HUAWEI BLN-AL40	Error	19722	AndroidRuntime	Process: com.android11.filemanager, PID: 19722

时间	设备名称	类型	PID	标记	消息
09-02 17:42:42.693	HUAWEI BLN-AL40	Error	19722	AndroidRuntime	java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.android11.filemanager.ui.category.storage.StoragePresenter.getJunkProcessSet(StoragePresenter.java)
	at com.android11.filemanager.ui.category.storage.StoragePresenter.startCleanTask(StoragePresenter.java)
	at com.android11.filemanager.ui.category.storage.StorageFragment.lambda$initListeners$0(StorageFragment.java)
	at com.android11.filemanager.ui.category.storage.StorageFragment.access$lambda$0(StorageFragment.java)
	at com.android11.filemanager.ui.category.storage.StorageFragment$$Lambda$1.onClick(Unknown Source)
	at com.jiepier.filemanager.widget.BoomView.onTouchEvent(BoomView.java)
	at android.view.View.dispatchTouchEvent(View.java:10012)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10232)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:356)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
