### ISSUE TITLE
7.0 清理系统垃圾 异常

### ISSUE THREAD

**Issue by Mr-Smile** [RuijiePan/FileManager#8]
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.jiepier.filemanager.manager.CleanManager.cleanAppsCache(CleanManager.java:121)
W/System.err:     at com.jiepier.filemanager.manager.CleanManager$2.call(CleanManager.java:89)
W/System.err:     at com.jiepier.filemanager.manager.CleanManager$2.call(CleanManager.java:84)
W/System.err: Caused by: java.lang.SecurityException: Neither user 10095 nor current process has android.permission.CLEAR_APP_CACHE.
W/System.err:     at android.os.Parcel.readException(Parcel.java:1683)
W/System.err:     at android.os.Parcel.readException(Parcel.java:1636)
W/System.err:     at android.content.pm.IPackageManager$Stub$Proxy.freeStorageAndNotify(IPackageManager.java:4566)

**Comment by Mr-Smile** [comment]
android.permission.CLEAR_APP_CACHE这个权限是加了的，直接拉你的代码，运行到手机上
compileSdkVersion 26
buildToolsVersion "26.0.2"
targetSdkVersion 26
classpath 'com.android.tools.build:gradle:2.3.3'
改了这几个，其他的代码没有动

**Comment by wfiskz** [comment]
这个异常是在6.0及以上会出现，请问有解决的吗
